name: Build image
'on':
  push:
    branches:
      - '!main'
  
jobs:
  build:
    name: Build image
    id: docker_build
    uses: docker/build-push-action@v2
    run: docker build -t groove-alpine .