name: release
on:
  push:
    branches:
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: docker build -t groove-alpine
      
