name: Build 

on:
  push:
    branches:
    - 'main'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: noc    
  GKE_ZONE: us-central1-a
  IMAGE: groove-alpine

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Configure Docker 
      run: |-
        gcloud --quiet auth configure-docker
        
    - name: Get The GKE credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --region us-central1
  
    - name: Retrieve docker image
      uses: actions/download-artifact@v2
      with: 
        name: docker-artifact
        path: /tmp/docker-backup
    
    - name: Docker load
      run: |
        cd /opt/docker-backup
        docker load < docker-image.tar
        
    - name: Docker build
      run: |
        docker ps
